# Generated by Django 4.2.4 on 2023-08-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='статус публикации'),
        ),
    ]