# Generated by Django 4.2.4 on 2023-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_ad',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]